h2:
  enabled: true
  enableAppServer: true #使用应用h2数据库
  data-path: classpath:data/data #entity
  relation-path: classpath:data/relation #关联表
  serverConfig: -tcp,-tcpPort,9095,-tcpAllowOthers,-ifNotExists,-baseDir,D:/h2/db
#debug: true
server:
  port: 8081
mybatis:
  #mapper-locations: classpath:mapper/user/UserOperation.xml
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    database-id: h2 
spring:
  mvc:
    favicon:
      enabled: false
  security:
    oauth: true #启用oauth
    enabled: true #是否拦截请求
    user:
      name: user
      password: user
      roles: admin
  cache:
    ehcache:
      config: classpath:ehcache-spring.xml
  data:
    elasticsearch:
      cluster-name: ltl
      cluster-nodes: localhost:9300 #必须填tcp port
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
  jpa:
    open-in-view: true #默认true，EntityManager在request期间绑定thread，防止懒加载错误
    show-sql: true    
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    
    first:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost:9095/./h2test
      username: sa
      password: ""
      a: a
    #druid:      
      #连接池等相关配置
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: stat,wall,log4j
      filters: stat,log4j #去掉防火墙，否则获取序列值报错
      initialSize: 13
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 'x'