h2.enabled: true
spring:
  security:
    user:
      name: user
      password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    first:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost/./h2test
      username: sa
      password: ""
    druid:      
      #连接池等相关配置
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: stat,wall,log4j
      initialSize: 13
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 'x'