#debug: true
server:
  port: 8080
mybatis:
  #mapper-locations: classpath:mapper/user/UserOperation.xml
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    database-id: h2
logging:
  level:
    com.bonc: info
config.profile: dev
spring:
  application:
    name: test
    admin:
      enabled: false
  profiles:
    active: #可被命令行参数重写。
    - dev #db、redis、es、rabbitmq连接信息
    include:
    - integrate #集成框架配置信息，自定义配置信息
  mvc:
    favicon:
      enabled: false
    date-format: dd-MM-yyyy
    
  security:
    oauth: false #启用oauth
    enabled: true #是否拦截请求
    user:
      name: user
      password: user
      roles: admin
  cache:
    ehcache:
      config: classpath:ehcache-spring.xml

  jpa:
    open-in-view: true #默认true，EntityManager在request期间绑定thread，防止懒加载错误
    show-sql: true    
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    
    first:
    #druid:      
      #连接池等相关配置
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: stat,wall,log4j
      filters: stat,log4j #去掉防火墙，否则获取序列值报错
      initialSize: 13
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 'x'
      db-type: H2
http-pool:
    connect-timeout: 5000
    connection-request-timeout: 1000
    default-max-per-route: 100
    max-total: 200
    socket-timeout: 65000
    validate-after-inactivity: 2000
---
spring: #db、redis、es、rabbitmq连接信息,username、password加密
  profiles: dev #声明当前块profile
  datasource:  
    first:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost:9095/./h2
      username: ENC(GMJOsvo+/haBEReVI+4LZg==)
      password: ENC(0Z96xwmyhA6KtCa7bG5NfA==)
  redis:
#    sentinel:
#      master: abc #master名称
#      nodes: #哨兵节点，host:port,
#    cluster:
#      max-redirects: 3
#      nodes: #集群节点，host:port,
    host: localhost
    port: 6379
    lettuce:
      pool: #common-pools对应参数
        max-active: 10
  data:
    elasticsearch:
      cluster-name: ltl
      cluster-nodes: localhost:9300 #必须填tcp port
      repositories:
        enabled: true
  rabbitmq:
    username: ENC(peVPISDBoSyYChlcct8r9w==)
    password: ENC(peVPISDBoSyYChlcct8r9w==)
    publisher-confirms: true
    template:
      retry:
        enabled: true         