h2:
  enabled: true
  enableAppServer: true #使用应用h2数据库
  data-path: classpath:data/data #entity
  relation-path: classpath:data/relation #关联表
  serverConfig: -tcp,-tcpPort,9095,-tcpAllowOthers,-ifNotExists,-baseDir,D:/h2/db
mybatis:
  #mapper-locations: classpath:mapper/user/UserOperation.xml
  mapper-locations: classpath:mapper/**/*.xml
spring:
  security:
    oauth: true #启用oauth
    enabled: true #是否拦截请求
    user:
      name: user
      password: user
      roles: admin
  cache:
    ehcache:
      config: classpath:ehcache-spring.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    
    first:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost:9095/./h2test
      username: li
      password: tianlin
    druid:      
      #连接池等相关配置
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: stat,wall,log4j
      initialSize: 13
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 'x'