h2:
  enabled: true
  enableAppServer: true #使用应用h2数据库
  data-path: classpath:data/data #entity
  relation-path: classpath:data/relation #关联表
  serverConfig: -tcp,-tcpPort,9095,-tcpAllowOthers,-ifNotExists,-baseDir,D:/h2/db
#debug: true
server:
  port: 8080
mybatis:
  #mapper-locations: classpath:mapper/user/UserOperation.xml
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    database-id: h2
management:
  cloudfoundry:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true        
  endpoint:    
    shutdown:
      enabled: true
    loggers:
      enabled: true
logging:
  level:
    com.bonc: info
spring:
  boot:
    admin:
      client:
        url: "http://localhost:9998"
  h2:
    console: #h2浏览器监控界面
      enabled: true
      path: /h2console
      settings:
        web-allow-others: true #远程访问
  rabbitmq:
    username: test
    password: test
    publisher-confirms: true
    template:
      retry:
        enabled: true
  jmx:
    default-domain: jmxmp
    enabled: true  
  
  mvc:
    favicon:
      enabled: false
  security:
    oauth: false #启用oauth
    enabled: true #是否拦截请求
    user:
      name: user
      password: user
      roles: admin
  cache:
    ehcache:
      config: classpath:ehcache-spring.xml
  data:
    elasticsearch:
      cluster-name: ltl
      cluster-nodes: localhost:9300 #必须填tcp port
      repositories:
        enabled: true
  redis:
#    sentinel:
#      master: abc #master名称
#      nodes: #哨兵节点，host:port,
#    cluster:
#      max-redirects: 3
#      nodes: #集群节点，host:port,
    host: localhost
    port: 6379
    lettuce:
      pool: #common-pools对应参数
        max-active: 10
  jpa:
    open-in-view: true #默认true，EntityManager在request期间绑定thread，防止懒加载错误
    show-sql: true    
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    
    first:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost:9095/./h2
      username: sa
      password: ""
      a: a
    #druid:      
      #连接池等相关配置
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: stat,wall,log4j
      filters: stat,log4j #去掉防火墙，否则获取序列值报错
      initialSize: 13
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 'x'
      db-type: H2
#httppool
http-pool:
    connect-timeout: 5000
    connection-request-timeout: 1000
    default-max-per-route: 100
    max-total: 200
    socket-timeout: 65000
    validate-after-inactivity: 2000